version: "3.7"

services:
  postgres:
    image: postgres:alpine
    container_name: rinhadebackend-cpp-drogon-postgres-dev
    restart: always
    environment:
      - POSTGRES_PASSWORD=fight
      - POSTGRES_DB=fight
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    network_mode: host
    tmpfs:
      - /run
    healthcheck:
      test: [ "CMD-SHELL", "[ -r /var/run/postgresql/ready ] || ( pg_isready && touch /var/run/postgresql/ready)" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.85'
          memory: '1.8GB'

volumes:
  postgres-dev-data: